
export const FETCH_JOB_LISTINGS_REQUEST = 'FETCH_JOB_LISTINGS_REQUEST';
export const FETCH_JOB_LISTINGS_SUCCESS = 'FETCH_JOB_LISTINGS_SUCCESS';
export const FETCH_JOB_LISTINGS_FAILURE = 'FETCH_JOB_LISTINGS_FAILURE';
export const APPLY_FILTERS = 'APPLY_FILTERS';
export const RESET_FILTERS = 'RESET_FILTERS';
export const UPDATE_HAS_NEXT_PAGE = 'UPDATE_HAS_NEXT_PAGE';
